#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

use UzDevid\WebSocket\Application;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/Config/bootstrap.php';
require __DIR__ . '/socket/Config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/Config/main.php',
    require __DIR__ . '/common/Config/Local/main.php',
    require __DIR__ . '/socket/Config/main.php',
);

$application = new Application($config);
$application->run();
